### ISSUE TITLE
模块中的find方法无法过滤多个字段

### ISSUE THREAD

**Issue by ldnn** [jonatasrenan/itoptop#7]
schema.py中第42行“utput_fields = ", ".join(projection)”在字符串拼接时多加入了一个空格，导致过滤多个字段时返回为空。去掉“,”后的空格即可：“utput_fields = ",".join(projection)”

**Comment by sulfuron** [comment]
敢问为何关闭了此issue？我也不明白这个地方

**Comment by ldnn** [comment]
使用的itop版本是2.6，把schema.py中第42行“utput_fields = ", ".join(projection)”空格去掉后就正常了：“utput_fields = ",".join(projection)”
